apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-websta
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8080
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 32Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - "https://websta.ansatt.nav.no"